[WIP] Add dropdown and confirm for comments button
Expensify/k2-extension pull request #158
Opened 2023-04-25 12:09 UTC by grgia

https://user-images.githubusercontent.com/38015950/234271751-da55f330-664c-4e88-887e-8a4576b7a3c3.mov

2023-04-25 13:03 UTC, grgia commented
@tgolen I branched from Lauren's branch [here](https://github.com/Expensify/k2-extension/pull/155), how would you suggest I handle merging these two PRs? Is it okay to close one or merge them?

2023-04-25 16:42 UTC, tgolen requested changes

2023-04-25 16:42 UTC, tgolen commented on src/js/module/K2comments/CommentsButtons.js
> +                        className="btn btn-sm send"
Let's add `btn-primary` to turn it green so it's not so easy to miss

2023-04-25 19:17 UTC, tgolen commented
> Actually, I realize I'd have to close the first branch regardless

Yeah, closing the other one is fine 👍

2023-04-26 09:14 UTC, grgia commented
cc @tgolen this is ready for another round! 

Also quick Q- should the selection clear if you close the dropdown?

Current behavior: 
Only clear selection after clicking the selection, closing the dropdown doesn't affect the selection

https://user-images.githubusercontent.com/38015950/234527606-803161cb-75e5-461e-96e2-151c0ff33841.mov

Alternative behavior: 
Clear selection after clicking the selection, and closing the dropdown clears the selection

https://user-images.githubusercontent.com/38015950/234527624-7bb383ae-d9be-4a4d-ba25-e08187fd33e7.mov

2023-04-26 16:24 UTC, tgolen commented
> Also quick Q- should the selection clear if you close the dropdown?

I think it's a tricky UX for sure. I actually think that neither proposals quite fix it. I had an idea that might help:

1. Click to open the drop-down
2. Selecting an option keeps the drop-down open and indicates which option was selected (maybe a green check icon, but that would mean we need to remove the green check icon for design docs, which I think is OK). You could also maybe change the border or background color of the option.
3. Once an option is selected, then the send button appears
4. Closing the drop-down clears all selections and hides the send button

2023-04-27 10:00 UTC, grgia commented
@tgolen here's a few quick options to illustrate:

We could change the title of the comments shortcuts button when one is selected:

![image](https://user-images.githubusercontent.com/38015950/234828036-9c9594f7-33c9-490f-bc18-9a0e24bd3c82.png)

otherwise, we could your suggestion using something like a checkbox and never hide the other options:

![image](https://user-images.githubusercontent.com/38015950/234828857-d6baf4c5-8d86-4c74-83f8-c5e5600eb879.png)

But I don't think the current branch UX is that confusing, we could also do nothing

2023-04-27 15:02 UTC, tgolen commented
> We could change the title of the comments shortcuts button when one is selected:

Oh, actually I love this one. Let's do it!

2023-04-28 16:07 UTC, grgia commented
@tgolen updated!

2023-04-28 16:22 UTC, tgolen approved these changes

2023-04-28 16:22 UTC, merged

2023-04-28 16:22 UTC, tgolen commented
Looks great, Thanks!