Style updates
Expensify/k2-extension pull request #181
Opened 2024-01-08 17:26 UTC by dangrous

$ https://github.com/Expensify/Expensify/issues/334627

This updates the design to match @dubielzyk-expensify's requests.

@tgolen I couldn't reproduce the [resetting of the filters](https://expensify.slack.com/archives/C03TQ48KC/p1699459489261079). Might that have been fixed with your recent 1.3.6 update? It looks like these remain static even when the new data is fetched.

2024-01-08 17:29 UTC, tgolen commented
Yeah, I agree. I haven't been able to reproduce the problem with the filters again either.

2024-01-09 02:38 UTC, thienlnam requested changes
Looking good, just one small comment

2024-01-09 02:38 UTC, thienlnam commented on src/css/content.scss
> +}
Looks like we are missing a new line here

2024-01-09 16:08 UTC, dangrous commented
updated!

2024-01-10 02:12 UTC, thienlnam approved these changes

2024-01-10 02:12 UTC, merged